# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: 'CD - agent'
  demands:
  - agent.name -equals DESKTOP-DAHBI

variables:
  buildConfigPath: 'src/main/resources/application.properties'
  artifactName: '$(Build.BuildNumber)-$(Build.DefinitionName).war'
  targetDirectory: 'C:\Users\PC\Desktop\TargetBackend'

steps:
- checkout: self

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean package'
    options: '-DskipTests=false'  # Ensure tests are not skipped
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
  displayName: 'Build and test the application'

- script: |
    copy $(Build.SourcesDirectory)\target\schoolhub-backend.war $(targetDirectory)
  displayName: 'Copy WAR file to target directory'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)\target\schoolhub-backend.war'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'