# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    chmod +x mvnw
    ./mvnw clean install
  displayName: 'Build and test with Maven'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true

- script: ./mvnw jib:dockerBuild -Djib.to.image=$(dockerRegistry)/$(imageName):$(Build.BuildId)
  displayName: 'Build and push Docker image'
  env:
    JAVA_HOME: $(JAVA_HOME_17_X64)
