# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: 'CD - agent'
  demands:
  - agent.name -equals DESKTOP-DAHBI

variables:
  buildConfigPath: 'src/main/resources/application.properties'
  artifactName: '$(Build.BuildNumber)-$(Build.DefinitionName).war'
  targetDirectory: 'C:\Users\PC\Desktop\TargetBackend'

steps:
- checkout: self

- script: |
    mvn package
  displayName: 'Build the application'
  workingDirectory: $(Build.SourcesDirectory)

- script: |
    copy $(Build.SourcesDirectory)\target\schoolhub-backend.war $(targetDirectory)
  displayName: 'Copy JAR file to target directory'