trigger:
- main

pool:
  name: 'CD - agent'
  demands:
  - agent.name -equals DESKTOP-DAHBI

variables:
  buildConfigPath: 'src/main/resources/application.properties'
  artifactName: '$(Build.BuildNumber)-$(Build.DefinitionName).war'
  targetDirectory: 'C:\Users\PC\Desktop\TargetBackend'

steps:
- checkout: self

- script: |
    mvn verify
  displayName: 'Build and test the application'
  workingDirectory: $(Build.SourcesDirectory)

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml'
    testRunTitle: 'Publish Test Results'
  displayName: 'Publish Test Results'

- script: |
    copy $(Build.SourcesDirectory)\target\schoolhub-backend-0.0.1-SNAPSHOT.jar $(targetDirectory)
  displayName: 'Copy JAR file to target directory'
  condition: succeeded()
